graph TB
    op[operation]:::previous -- can have --> closure:::previous
    op -- can have --> identity:::previous
    op -- can have --> associativity:::previous
    op -- can have --> commutativity:::previous
    op -- can have --> distributivity:::previous
    op -- can have --> inverse:::previous


    scalar -- forms --> field

    scalar:::previous -- can scale --> vector:::previous

    vector:::today -- forms --> group
    vector -- pairs have --> dp[dot product]
    dp -- defines --> orthogonal
    vector -- can be --> normalised
    normalised -- with --> norm
    vs -- has --> axioms

    vs -- has set of --> scalar
    vs -- allows --> lincomb[linear combination]
    vs[vector space]:::today -- has --> vectorset:::today

    vs -- has --> basis:::today

    vs -- has --> dimension:::today

    vectorset -- contains --> vector
    basis -- spans --> vs
    lincomb::today -- of --> scalar
    lincomb -- of --> vectorset
    field:::previous -- has --> axioms
    group:::previous -- has --> axioms
    field -- includes --> group

    basis -- is a --> vectorset
    basis -- size defines --> dimension
    basis -- can be -->orthonormal
    orthonormal -- requires --> normalised

    orthonormal -- requires --> orthogonal
    dp -- defines a --> norm

    lm[linear map] -- acts on --> vector
    matrix -- represents --> lm
    matrix -- has --> determinant
    determinant -- nonzero implies --> inverse
    matrix -- can represent --> lineq[system of linear equations]
    ge[Gaussian elimination] -- acts on --> matrix
    ge -- reduces matrix to --> ref[row-echelon form]
    matrix -- can have --> ref
    matrix -- can be --> diagonal

    vectorset[set of vectors]
    vectorset -- can have --> indep[linear independence]
    basis -- has --> indep
    lm -- has --> rank
    lm -- has --> kernel
    ge -- can find --> inverse
    axioms:::previous -- govern --> op

classDef previous fill:#f9f,stroke:#000,stroke-width:4px;
classDef previous fill:#fff,stroke:#000,stroke-width:4px;