graph TB
    op[operation]:::previous -- can have --> closure:::previous
    op -- can have --> identity:::previous
    op -- can have --> associativity:::previous
    op -- can have --> commutativity:::previous
    op -- can have --> distributivity:::previous
    op -- can have --> inverse:::previous


    scalar -- belongs to --> field

    scalar:::today -- can scale --> vector


    vector:::today -- has  --> add
    vector -- pairs have --> dp[dot product]
    dp -- defines --> orthogonal
    vector -- can be --> normalised
    normalised -- with --> norm
    vs:::today -- has --> axioms

    vs -- has set of --> scalar
    vs -- allows --> lincomb[linear combination]
    vs[vector space] -- has --> vectorset

    vs -- has --> basis

    vs -- has --> dimension

    vectorset:::today -- contains --> vector
    basis:::today -- spans --> vs
    lincomb:::today -- of --> scalar
    lincomb -- of --> vectorset
    field:::previous -- has --> axioms
    group:::previous -- has --> axioms
    field -- includes --> group

    field -- has --> add
    field -- has  --> times
    basis -- is a --> vectorset
    basis -- size defines --> dimension:::today
    basis -- can be -->orthonormal
    orthonormal -- requires --> normalised

    orthonormal -- requires --> orthogonal
    dp -- defines a --> norm


    


lm[linear map] -- acts on --> vector
matrix -- represents --> lm
matrix -- has --> add
matrix -- has --> times
matrix -- has --> determinant
determinant -- nonzero implies --> inverse
matrix -- can represent --> lineq[sytem of linear equations]
ge[Gaussian elimination] -- acts on --> matrix
ge -- reduces matrix to --> ref[row-echelon form]
matrix -- can have --> ref
matrix -- can be --> diagonal

vectorset[set of vectors]
vectorset -- can have --> indep[linear independence]:::today
basis -- has --> indep
lm -- has --> rank
lm -- has --> kernel
add[addition]:::previous -- is a --> op
times[multiplication]:::previous -- is a --> op
ge -- can find --> inverse
axioms:::previous -- govern --> op

classDef today fill:#f9f,stroke:#000,stroke-width:4px;
classDef previous fill:#fff,stroke:#000,stroke-width:4px;